# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttm" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2348f0068ecd0d25fc04973372c1e7ade90f73c8bc3877b54a5d8d32ca53a59b"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "d65ca493e18e7ea0a08c47ecc54a94ec4e133dba91ac24dcb88337b6c8deb073"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_arm64.zip"
    end
  end

  name "ttm"
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttm"

  # No zap stanza required

end
