# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttm" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "08b49c1e2cfba2db22ffb3ddd52d727c302232f3497f662b818efa1bbf587e6a"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "8a01ed9ebf43e0b6d3deb39866afd7c9c927fe87c893621c6eb4116370aebecf"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_arm64.zip"
    end
  end

  name "ttm"
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttm"

  # No zap stanza required

end
