# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3edd859edbd3da7a1d342c1436c86ade32fb5473bf72ab26d4b0e7c50c98931f"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "2ac4db58a61eca002aefccd53fb4f6bfab188bc2d0d9c83fcd2ddcc3f13846ae"
      url "https://github.com/mulvad/ttm/releases/download/v#{version}/ttm_#{version}_darwin_arm64.zip"
    end
  end

  name "ttm"
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttm"

  # No zap stanza required

end
