# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttm < Formula
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_amd64.tar.gz"
    sha256 "387aba47780affdba54cf971b0728ebf666cdb725cb5cad954425487aa34bb3e"

    define_method(:install) do
      bin.install "ttm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_arm64.tar.gz"
    sha256 "531f67c8a241bb7cb7946db3321d25b4e61e71ee0269542ea88cf5e6bc96fd6a"

    define_method(:install) do
      bin.install "ttm"
    end
  end

  test do
    system "#{bin}/ttm", "--version"
  end
end
