# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttm < Formula
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_amd64.tar.gz"
    sha256 "cf811e14ffdadc554c7a2e7b6b7671847c0edda636db02ea0d2a1a7c7ee50468"

    define_method(:install) do
      bin.install "ttm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_arm64.tar.gz"
    sha256 "e98e8a73c052ab5908a90a1b41304de00ce9afdccc5c96f21fea6985a7d7b27c"

    define_method(:install) do
      bin.install "ttm"
    end
  end

  test do
    system "#{bin}/ttm", "--version"
  end
end
