# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttm < Formula
  desc "Terminal Theme Manager - manage terminal themes based on project context"
  homepage "https://github.com/mulvad/ttm"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_amd64.tar.gz"
    sha256 "315ba25b3a24319ab7801ef7f98587fab0867137b8934840cb7797d34ed34c90"

    define_method(:install) do
      bin.install "ttm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/mulvad/ttm/releases/download/v0.1.0/ttm_0.1.0_darwin_arm64.tar.gz"
    sha256 "1dcecc75405dcde3dd6484011492ef2f65c88379553a065b9a52ce3bf38f4ba1"

    define_method(:install) do
      bin.install "ttm"
    end
  end

  test do
    system "#{bin}/ttm", "--version"
  end
end
